# -------------------------------------------------
# KitPvP
# Version: ${project.version}
#
# Created by: Foulest (https://github.com/Foulest/KitPvP)
# License: GPLv3 (https://github.com/Foulest/KitPvP/LICENSE)
# -------------------------------------------------
kitpvp:
  # -----------------------------------------------
  # Spawn Settings
  # These can be set in-game using /setspawn.
  # -----------------------------------------------
  # world: The world name of the spawn.
  # x: The x coordinate of the spawn.
  # y: The y coordinate of the spawn.
  # z: The z coordinate of the spawn.
  # yaw: The yaw of the spawn.
  # pitch: The pitch of the spawn.
  spawn:
    world: world
    x: 0.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  # -----------------------------------------------
  # Combat Tag Settings
  # -----------------------------------------------
  # enabled: Whether or not combat tag is enabled.
  # duration: The duration of combat tag in seconds.
  # cancel-teleport: Whether or not to cancel teleportation when combat tagged.
  # punish-logout: Whether or not to punish players for logging out while combat tagged.
  # deny-entering-spawn: Whether or not to deny players from entering spawn while combat tagged.
  combat-tag:
    enabled: true
    duration: 15
    cancel-teleport: true
    punish-logout: true
    deny-entering-spawn: true
  # -----------------------------------------------
  # Bounties Settings
  # -----------------------------------------------
  # enabled: Whether or not bounties are enabled.
  bounties:
    enabled: true
    cooldown: 60
    max-amount: 1000
  # -----------------------------------------------
  # Economy Settings
  # -----------------------------------------------
  # starting-coins: The amount of coins players start with.
  # coins-on-kill: The amount of coins players receive on kill.
  # exp-on-kill: The amount of experience players receive on kill.
  economy:
    starting-coins: 500
    coins-on-kill: 10
    exp-on-kill: 15
  # -----------------------------------------------
  # Killstreak Settings
  # Bonus coins and experience scale with the size of the killstreak.
  # -----------------------------------------------
  # enabled: Whether or not killstreaks are enabled.
  # coins-bonus: The amount of bonus coins players receive on a killstreak.
  # exp-bonus: The amount of bonus experience players receive on a killstreak.
  killstreaks:
    enabled: true
    coins-bonus: 5
    exp-bonus: 10
  # -----------------------------------------------
  # Kit Enchanter Settings
  # -----------------------------------------------
  # enabled: Whether or not the Kit Enchanter is enabled.
  # enchant.enabled: Whether or not an Enchant is enabled.
  # enchant.cost: The cost of the Enchant.
  kit-enchanter:
    enabled: true
    feather-falling:
      enabled: true
      cost: 100
    thorns:
      enabled: true
      cost: 100
    protection:
      enabled: true
      cost: 100
    knockback:
      enabled: true
      cost: 100
    sharpness:
      enabled: true
      cost: 100
    punch:
      enabled: true
      cost: 100
    power:
      enabled: true
      cost: 100
  # -----------------------------------------------
  # Storage Settings
  # SQLite and MariaDB are supported.
  # -----------------------------------------------
  # type: The type of the database. (sqlite, mariadb)
  # auto-save: The interval of the database auto-save in seconds.
  # sqlite.file: The file path of the database.
  # mariadb.host: The hostname of the database.
  # mariadb.port: The port of the database.
  # mariadb.database: The name of the database.
  # mariadb.username: The username of the database.
  # mariadb.password: The password of the database.
  storage:
    type: sqlite
    auto-save: 300
    sqlite:
      file: plugins/KitPvP/database.db
    mariadb:
      host: hostname
      port: 3306
      database: kitpvp
      username: username
      password: password
  # -----------------------------------------------
  # Kit Settings
  # Below are all the kits players can choose from.
  # -----------------------------------------------
  # enabled: Whether or not the kit is enabled.
  # cost: The cost of the kit.
  # cooldown: The cooldown of the kit's ability.
  # duration: The duration of the effects of the kit's ability.
  # range: The range of the effects of the kit's ability.
  # damage: The damage of the effects of the kit's ability.
  # multiplier: The multiplier of the effects of the kit's ability.
  # height: The height of the effects of the kit's ability.
  # amount: The amount of the effects of the kit's ability.
  kits:
    knight:
      enabled: true
      cost: 0
    archer:
      enabled: true
      cost: 250
    burrower:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 10
    cactus:
      enabled: true
      cost: 250
      passive:
        duration: 5
    dragon:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 8
        range: 6
        damage: 8
    fisherman:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
    ghost:
      enabled: true
      cost: 250
      ability:
        range: 6
    hulk:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        range: 6
        damage: 10
        multiplier: -4.0
    imprisoner:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 4
        damage: 4
        height: 9
    kangaroo:
      enabled: true
      cost: 250
      ability:
        cooldown: 20
        sneaking:
          height: 0.3
          multiplier: 2.5
        normal:
          height: 1.2
          multiplier: 0.0
    mage:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
    monk:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
    ninja:
      enabled: true
      cost: 250
    pyro:
      enabled: true
      cost: 250
    spiderman:
      enabled: true
      cost: 250
      ability:
        cooldown: 15
        duration: 5
    summoner:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 10
        range: 15
    tamer:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 10
        amount: 3
    tank:
      enabled: true
      cost: 250
    thor:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 5
        range: 6
        damage: 10
    timelord:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 5
        range: 6
    vampire:
      enabled: true
      cost: 250
      passive:
        duration: 5
      ability:
        cooldown: 30
        duration: 10
        range: 6
    zen:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 5
        range: 25
