# KitPvP
# Version: ${project.version}
#
# Created by: Foulest (https://github.com/Foulest/KitPvP)
# License: GPLv3 (https://github.com/Foulest/KitPvP/LICENSE)
kitpvp:
  spawn:
    world: "world"
    x: 0.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  combat-tag:
    enabled: true
    duration: 15
    cancel-teleport: true
    punish-logout: true
    deny-entering-spawn: true
  economy:
    starting-coins: 500
    coins-on-kill: 10
    exp-on-kill: 15
  killstreaks:
    enabled: true
    coins-bonus: 5
    exp-bonus: 10
  kit-enchanter:
    enabled: true
    feather-falling:
      enabled: true
      cost: 100
    thorns:
      enabled: true
      cost: 100
    protection:
      enabled: true
      cost: 100
    knockback:
      enabled: true
      cost: 100
    sharpness:
      enabled: true
      cost: 100
    punch:
      enabled: true
      cost: 100
    power:
      enabled: true
      cost: 100
  storage:
    host: "hostname"
    port: 3306
    database: "kitpvp"
    username: "username"
    password: "password"
  kits:
    knight:
      enabled: true
      cost: 0
    archer:
      enabled: true
      cost: 250
    burrower:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 10
    cactus:
      enabled: true
      cost: 250
      passive:
        duration: 5
    dragon:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 8
        range: 6
        damage: 8
    fisherman:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
    ghost:
      enabled: true
      cost: 250
      ability:
        range: 6
    hulk:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        range: 6
        damage: 10
        multiplier: -4.0
    imprisoner:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 4
        damage: 4
        height: 9
    kangaroo:
      enabled: true
      cost: 250
      ability:
        cooldown: 20
        sneaking:
          height: 0.3
          multiplier: 2.5
        normal:
          height: 1.2
          multiplier: 0.0
    mage:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
    monk:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
    ninja:
      enabled: true
      cost: 250
    pyro:
      enabled: true
      cost: 250
    spiderman:
      enabled: true
      cost: 250
      ability:
        cooldown: 15
        duration: 5
    summoner:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 10
        range: 15
    tamer:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 10
        amount: 3
    tank:
      enabled: true
      cost: 250
    thor:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 5
        range: 6
        damage: 10
    timelord:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 5
        range: 6
    vampire:
      enabled: true
      cost: 250
      passive:
        duration: 5
      ability:
        cooldown: 30
        duration: 10
        range: 6
    zen:
      enabled: true
      cost: 250
      ability:
        cooldown: 30
        duration: 5
        range: 25
