# -------------------------------------------------
# KitPvP
# Version: ${project.version}
#
# Created by: Foulest (https://github.com/Foulest/KitPvP)
# License: GPLv3 (https://github.com/Foulest/KitPvP/LICENSE)
# -------------------------------------------------
kitpvp:
  # -----------------------------------------------
  # Spawn Settings
  #
  # These can be set in-game using /setspawn.
  # -----------------------------------------------
  spawn:
    world: world
    x: 0.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  # -----------------------------------------------
  # Combat Tag Settings
  # -----------------------------------------------
  combat-tag:
    enabled: true
    duration: 15
    cancel-teleport: true
    punish-logout: true
    deny-entering-spawn: true
  # -----------------------------------------------
  # Bounties Settings
  # -----------------------------------------------
  bounties:
    enabled: true
    cooldown: 60
    min-amount: 50
    max-amount: 1000
  # -----------------------------------------------
  # Economy Settings
  # -----------------------------------------------
  economy:
    starting-coins: 500
    coins-on-kill: 10
    exp-on-kill: 15
  # -----------------------------------------------
  # Killstreak Settings
  #
  # Bonus coins and experience scale
  # with the size of the killstreak.
  # -----------------------------------------------
  killstreaks:
    enabled: true
    coins-bonus: 5
    exp-bonus: 10
  # -----------------------------------------------
  # Kit Enchanter Settings
  # -----------------------------------------------
  kit-enchanter:
    enabled: true
    feather-falling:
      enabled: true
      cost: 100
    thorns:
      enabled: true
      cost: 100
    protection:
      enabled: true
      cost: 100
    knockback:
      enabled: true
      cost: 100
    sharpness:
      enabled: true
      cost: 100
    punch:
      enabled: true
      cost: 100
    power:
      enabled: true
      cost: 100
  # -----------------------------------------------
  # Storage Settings
  #
  # SQLite and MariaDB are supported.
  # -----------------------------------------------
  storage:
    type: sqlite
    sqlite:
      file: database.db
    mariadb:
      host: hostname
      port: 3306
      database: kitpvp
      username: username
      password: password
  # -----------------------------------------------
  # Kit Settings
  # -----------------------------------------------
  kits:
    archer:
      enabled: true
      cost: 250
      ability:
        cooldown: 20
        duration: 3
    fisherman:
      enabled: true
      cost: 250
      ability:
        cooldown: 20
    kangaroo:
      enabled: true
      cost: 250
      ability:
        cooldown: 20
    knight:
      enabled: true
      cost: 0
    mage:
      enabled: true
      cost: 250
      ability:
        cooldown: 20
    ninja:
      enabled: true
      cost: 250
      ability:
        cooldown: 20
        duration: 3
    pyro:
      enabled: true
      cost: 250
      ability:
        cooldown: 20
        duration: 5
        damage: 6.0
    tank:
      enabled: true
      cost: 250
      ability:
        cooldown: 20
        duration: 5
    vampire:
      enabled: true
      cost: 250
      ability:
        cooldown: 20
        duration: 5
