name: KitPvP
version: ${project.version}
main: net.foulest.kitpvp.KitPvP
author: Foulest
depend: [ PlaceholderAPI, WorldEdit, WorldGuard ]
loadbefore: [ Essentials ]
permissions:
  kitpvp.armorcolor:
    description: Allows players to change the color of their armor.
    default: op
  kitpvp.balance:
    description: Allows players to check their balance.
    default: true
  kitpvp.bounties:
    description: Allows players to use the bounty command.
    default: true
  kitpvp.bounties.place:
    description: Allows players to place bounties on other players.
    default: op
  kitpvp.clearkit:
    description: Allows players to clear their kit.
    default: true
  kitpvp.clearkit.others:
    description: Allows players to clear other players' kits.
    default: op
  kitpvp.combattag:
    description: Allows players to see their combat tag timer.
    default: true
  kitpvp.eco:
    description: Allows players to manage the economy.
    default: op
  kitpvp.eco.give:
    description: Allows players to give money to other players.
    default: op
  kitpvp.eco.set:
    description: Allows players to set other players' balances.
    default: op
  kitpvp.eco.take:
    description: Allows players to take money from other players.
    default: op
  kitpvp.kitenchanter:
    description: Allows players to use the kit enchanter.
    default: true
  kitpvp.kitselector:
    description: Allows players to use the kit selector.
    default: true
  kitpvp.kitshop:
    description: Allows players to use the kit shop.
    default: true
  kitpvp.main:
    description: Allows players to use the main command.
    default: true
  kitpvp.pay:
    description: Allows players to pay other players.
    default: true
  kitpvp.potions:
    description: Allows players to use potions.
    default: true
  kitpvp.reload:
    description: Allows players to reload the config.
    default: op
  kitpvp.setspawn:
    description: Allows players to set the spawn.
    default: op
  kitpvp.soup:
    description: Allows players to use soup.
    default: true
  kitpvp.spawn:
    description: Allows players to use the spawn command.
    default: true
  kitpvp.stats:
    description: Allows players to see their stats.
    default: true
  kitpvp.modify:
    description: Allows players to modify the map.
    default: op
